# Numpy in Detail

In [1]:
#Import Numpy
import numpy as np
np.array([4.2,5,6.5,7,8.9])

array([4.2, 5. , 6.5, 7. , 8.9])

In [25]:
#Data Types in numpy
result = np.array([2,3.6,4,5]) #Default
print(result,result.dtype)

result = np.array([2,3,4,5], dtype="int8") #Integer 8 array
print(result,result.dtype)

result = np.array([2,3,4,5], dtype="int64") #Default Integer 64 array
print(result,result.dtype)

result = np.array([2.3,8,4,5], dtype="float32") #float 32 array
print(result,result.dtype)

result = np.array([2.3,8,4,5], dtype="float64") #float 64 array
print(result,result.dtype)


result = np.array([2.3,8,4,5], dtype="str") #String array
print(result,result.dtype,"str")

[2.  3.6 4.  5. ] float64
[2 3 4 5] int8
[2 3 4 5] int64
[2.3 8.  4.  5. ] float32
[2.3 8.  4.  5. ] float64
['2.3' '8' '4' '5'] <U3 str


In [46]:
#Creating arrays - single and multidiemnstional
result = np.zeros(20, dtype="int") #Integer array filled with zeros
print(result,result.dtype,"\n")

result = np.zeros((6,10), dtype="float") #Integer array filled with zeros
print(result,result.dtype,"\n")

result = np.ones((4,12), dtype="float") #float array filled with 1s
print(result,result.dtype,"\n")

result = np.full((6,4), 4.15) #float array filled with 4.15
print(result,result.dtype,"\n")

result = np.arange(0,40,3) #array filled with a linear sequence, stepping by 3
print(result,result.dtype,"\n")

result = np.linspace(0,2,5) #array of five values evenly soaced between 0 and 2
print(result,result.dtype,"\n")

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] int32 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] float64 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] float64 

[[4.15 4.15 4.15 4.15]
 [4.15 4.15 4.15 4.15]
 [4.15 4.15 4.15 4.15]
 [4.15 4.15 4.15 4.15]
 [4.15 4.15 4.15 4.15]
 [4.15 4.15 4.15 4.15]] float64 

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39] int32 

[0.  0.5 1.  1.5 2. ] float64 



In [51]:
# Multi dimenstional array
result = np.random.random((3,3)) #3*3 array of unifromly distributed random values between 0 and 1
print(result,result.dtype,"\n")

result = np.random.normal(0,1,(3,3)) #3*3 array of unifromly distributed random values with mean 0 and SD 1
print(result,result.dtype,"\n")

result = np.random.randint(10,20,(4,4)) #3*3 array of unifromly distributed random values with mean 0 and SD 1
print(result,result.dtype,"\n")

result = np.eye(3) #3*3 array of Identity matrix
print(result,result.dtype,"\n")

[[0.62585519 0.94858954 0.96386637]
 [0.31318805 0.67311707 0.28312517]
 [0.42306181 0.87955659 0.39982745]] float64 

[[ 1.38518939 -2.04361462  0.11314428]
 [-0.50306258 -1.62065112  0.79584813]
 [-1.84144124  0.32273456 -0.49907856]] float64 

[[18 17 18 13]
 [13 16 13 17]
 [16 18 17 11]
 [14 17 19 15]] int32 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] float64 



In [65]:
#Array indexing 
result = np.array([2,3,4,5]) #Default
print(result,result.dtype,"\n")

print(result[0],"\n") #First element
print(result[-1],"\n") #Last element

result = np.random.randint(10,20,(4,4)) #3*3 array of unifromly distributed random values with mean 0 and SD 1
print(result,result.dtype,"\n")
print(result[2,1],"\n")

grid = np.arange(1,10,1).reshape(3,3)
print(grid)

x = np.array([2,5,7])
x.shape                # X is a vector

x.reshape((3,1))

[2 3 4 5] int32 

2 

5 

[[12 14 13 10]
 [10 12 15 17]
 [12 11 19 18]
 [15 17 15 18]] int32 

11 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2],
       [5],
       [7]])

In [73]:
#Numpy's UFuncs exist in two flavors
#unary ufuncs - Operate on a single input
#Binary ufuncs - Opeate on two inputs 

print("Python Arthmetic operations")
x = np.arange(4)
print(x)
print(x+5)
print(x-5)
print(x*2)
print(x/2)
print(x//2)
print(-x)
print(x ** 2)
print(x % 2)
print(-(0.5*x+1) ** 2)
print("\n")

print("Numpy Arthmetic operations")
print(x)
print(np.add(x,5))
print(np.subtract(x,5))
print(np.multiply(x,2))
print(np.divide(x,2))
print(np.floor_divide(x,2))
print(np.negative(x))      
print(np.power(x,2))
print(np.mod(x,2))

Python Arthmetic operations
[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[ 0 -1 -2 -3]
[0 1 4 9]
[0 1 0 1]
[-1.   -2.25 -4.   -6.25]


Numpy Arthmetic operations
[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[ 0 -1 -2 -3]
[0 1 4 9]
[0 1 0 1]


In [78]:
#Trigonmetric functions
print("Trigonmetric functions")
x = np.linspace(0,np.pi,3)

print(x)
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print("\n")
#Trig functions on arrays
print("Trig functions on arrays")
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))


Trigonmetric functions
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Trig functions on arrays
[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


In [79]:
#Broadcasting - It is simpy a set of rules for applying binary ufuncs(add, sub, multiply etc) on arrays of different sizes

a = np.array([2,1,5])
b = np.array([8,1,6])
print(a+b)

[10  2 11]


In [83]:
#Comparision operators

x = np.array([2,4,6,8])
print(x<3)
print(x>3)
print(x<=3)
print(x>=3)
print(x!=3)
print(x==3)

[ True False False False]
[False  True  True  True]
[ True False False False]
[False  True  True  True]
[ True  True  True  True]
[False False False False]
